### ISSUE TITLE
Confirmed working on 3DS ver. 10.5.0-30

### ISSUE THREAD

**Issue by Maverynthia** [Matthew-Hsu/PiPass#59]
I just got my CanaKit Pi 2 (from the link on the main page) with the Canakit Wifi stick that comes with it set up and imaged and it SEEMS to be working as intended. I passed a few hotspots and got a dump of streetpasses for various software. :dancers: 

Still trying to figure out the spreadsheet to add the personal MACs from the HomePass doc.

I guess this a non-issue, but for those curious 

I  guess features might be nice:
1. Being able to move onto a different sheet when done with current sheet, like move from the Personal MACs to the Nintendo ones
2. Ability to change from Mario to Waluigi ;3 

EDIT: Issues:
PiPass is telling me that my hardware is incompatible when I am trying to cycle the "[4] Mii colors and Genders" because the address looks like "4E:53:50:4F:42:00-0F" with that last "-0F" at the end.

**Comment by sheepluva** [comment]
"4E:53:50:4F:42:00-0F" is not an actual address, but most likely supposed to be shorthand for a range of addresses. 

So because in the used notation ("hexadecimal") numbers go 0,1,2,3,4,5,6,7,8,9,A,B,C,D,E,F the above range is supposed to mean that you'll have to write down these following 16 addresses in your custom sheet:

4E:53:50:4F:42:00
4E:53:50:4F:42:01
4E:53:50:4F:42:02
4E:53:50:4F:42:03
4E:53:50:4F:42:04
4E:53:50:4F:42:05
4E:53:50:4F:42:06
4E:53:50:4F:42:07
4E:53:50:4F:42:08
4E:53:50:4F:42:09
4E:53:50:4F:42:0A
4E:53:50:4F:42:0B
4E:53:50:4F:42:0C
4E:53:50:4F:42:0D
4E:53:50:4F:42:0E
4E:53:50:4F:42:0F

You could of course always decide to only include a sub-list or just the first one in your list, rather than all 16 addresses.
Just keep in mind that each 3DS will wait at least 8 hours (as far as I remember) to revisited an already visited address - so more is better :)
