### ISSUE TITLE
Remote Access to Raspberry Pi (Other than Dashboard)

### ISSUE THREAD

**Issue by itanimo** [Matthew-Hsu/PiPass#60]
Hi,

I bought a brand new Raspberry Pi 2 and flashed the PiPass image on the sd card. I have a question, is it possible for me to access the Pi's terminal remotely through my pc so I can just login to PiPass? Its a hassle to connect a keyboard and a monitor/tv each time I restart the Pi.

thanks

**Comment by jmctune** [comment]
Hi Safo91,

This isn't an issue and can already be accomplished.

You need to know your Raspberry Pi's IP address in order to accomplish this:
- Connect your Raspberry Pi to your home network
- Download PuTTY (will assume you are on Windows: http://the.earth.li/~sgtatham/putty/latest/x86/putty.exe) on your computer
- Launch PuTTY and enter your Raspberry Pi's IP address 
- Don't change anything else and click connect
- Accept the security warning about fingerprints that comes up
- Log in with the username root and password listed within the README (unless you changed it)
