### ISSUE TITLE
Preferences Do Not Save

### ISSUE THREAD

**Issue by brandonhines** [Matthew-Hsu/PiPass#67]
I just installed PiPass on a CanaKit linked from the main page. When I update PiPass DB Key or add my 3DS' MAC address the information does not get saved. I tried saving each field individually and it always resets to the default DB Key and a blank whitelist.

The issue persists after rebooting the hardware.

Any ideas?

**Comment by nagledb** [comment]
The dashboard sometimes has caching issues. Try doing a shift-refresh, perhaps they're changing and it just isn't showing the change. If that doesn't work...

When you change settings, the website first writes them out to a temp file and then copies them into the correct final place. I recommend that you ssh into the pipass and run the following commands to better see what's happening. (None of the files end in a newline, so I put "echo" after each line so that the output is more readable.)

The MAC addresses are first written here:
`cat /tmp/mac_accept ; echo`
And then are copied here:
`cat /etc/hostapd/mac_accept ; echo`

The DB Key and most other settings are first written here:
`cat /tmp/pipass_config.json ; echo`
And then are copied here:
`cat /var/www/assets/json/pipass_config.json ; echo`

Do you see your changes in the /tmp files? If so, do you see them in the other files?
