### ISSUE TITLE
User and Password infinite loop error. 

### ISSUE THREAD

**Issue by NGamerCole** [Matthew-Hsu/PiPass#82]
Basically this is what happens. I go to enter the User, I type it in just fine and press enter. Then when it gets on the password, I can't type anything at all, the only thing I can type in first is the enter key which will put it to the next line down and it's taking it as the whole password. And it just loops this over and over. 

I formatted the microSD card and followed the instructions, so I'm guessing there is some particular error?

**Comment by NGamerCole** [comment]
Anything?

**Comment by hackerx31337** [comment]
If i understand you correctly your problem is that you don't have a problem, just a misunderstanding. I'm guessing this is your first time dealing with Linux. The password prompt is supposed to stay blank no matter what you type. It is a security feature. Not only can somebody watching not tell what the password you are entering is, they can't even see how long it is.

**Comment by person65278** [comment]
What hacker said..... Type the password hit enter you wont see anything you typed and you will be logged in as long as you typed the correct password.

**Comment by Corruptinglyneedful** [comment]
There a way to disable this?

Confused me too, never used to do that.
